### ISSUE TITLE
Would be great to handle google apps as @gmail

### ISSUE THREAD

**Issue by tttp** [mc0e/civicrm-extendedmailingstats#1]
Hi,

So I'm assuming the separate tracking for gmail is about the new tabs and to avoid ending up trapped into the "promotions" tab, or whatever the name of where they put all the mass mailings.

So in that case, it would be great to not only track on %@gmail.com only but do a dns mx and check if it has a ASPMX.L.GOOGLE.COM. in it, as google apps have the same issues as the gmail ones

X+

**Comment by mc0e** [comment]
We've had problems with google's treating mail as spam, so it's not specific to the (newer) issues with the promotions tab.  We just generally want to keep a close eye on the stats for google users.

You're right that the google apps stuff means that google mail users aren't necessarily @gmail.com addresses.  If the @gmail.com addresses are at least representative of what's going on with google's mail handling though then it may not matter?  It would matter if you're trying to look at stats for non-google users as opposed to all users as a baseline for comparison.  Maybe other reasons.  I'm interested to know more of what you think you'd get out of adding this? 

For efficiency, there would want to be some caching of data on which domains use google mail.   We wouldn't want to be looking up dns data for thousands of domains on every run.

Also domains may or may not have used google mail at the time of some past mailing, so to really do it right you'd have to store historical data on when domains used google mail, and/or improve the algorithms so that only stats on recent mailings are being updated in the table of stored data that this extension uses.  The way things are structured, that's not too hard to do.  It's already contemplated but it's not currently implemented.

**Comment by mc0e** [comment]
I can't see myself implementing this, unless someone wants to fund it.

Closing.
